name: ci
on:
  push:
    branches: [ "main" ]   # change if your default branch differs

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, GitHub Actions!"
